<html>
<head>
<script src="http://libs.baidu.com/jquery/1.10.2/jquery.min.js">
</script>
<link rel="stylesheet" type="text/css" href="mystyle.css" />
        <link rel="stylesheet" type="text/css" href="js/easyui.css">
        <link rel="stylesheet" type="text/css" href="js/icon.css">
        <link rel="stylesheet" type="text/css" href="js/demo.css"> 
   <title>Scenario Testing Builder</title>
   <link href="http://libs.baidu.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet">
   <script src="http://libs.baidu.com/jquery/2.0.0/jquery.min.js"></script>
   <script src="http://libs.baidu.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
   <script type="text/javascript" src="js/jquery-1.6.min.js"></script>
   <script type="text/javascript" src="js/jquery.easyui.min.js"></script>

</head>
	<body>
       <?php include 'navigators4.php'; ?>
<h3 style="background-color:#EEEEEE;text-align:left;height:5%;width:80%"> &nbsp Test Steps </h3>
<br>
<br>
Step1. Select Device, you can add new device(Not necessarily) or select Next Step. 
<br>
<br>
<br>
Step2. Select Config, if you don't have config to commit, select Next Step directly.
<br>
<br>
<br>
Step3. Select Traffic, then submit. 
<br>
<br>

<h3 style="background-color:#EEEEEE;text-align:left;height:5%;width:80%"> &nbsp Upload Script </h3>
Used to submit script generated by tester such as IXIALOAD, BPS,etc. 
<br>
	</body>
</html>
